name: Pylint
  
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - run: pytest tests
    - run: mypy src/
    - run: black --diff --check src/
    - run: isort --check-only src/
    - run: flake8 src/
    
